import { test as base, expect } from './manual-note-fixture';

type MapFixture = { id: string; nodeId: string; title: string };
const test = base.extend<{ map: MapFixture }>({ map: async ({ request }, use) => {
  const { roadmap } = await (await request.post('/api/roadmaps', { data: { title: '人間が保存する地図' } })).json(); const { node } = await (await request.post('/api/nodes', { data: { roadmapId: roadmap.id, title: '選択中の項目A', learningObjectives: ['初期目標'] } })).json();
  try { await use({ id: roadmap.id, nodeId: node.id, title: roadmap.title }); } finally { await request.delete(`/api/roadmaps/${roadmap.id}`); }
} });

for (const kind of ['map','node'] as const) for (const current of ['same','different'] as const) test(`${kind} lost committed reply and ${current} current content require acknowledgment while keeping later human edits`, async ({ page, request, map }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto(`/workspaces/default/roadmaps/${map.id}`); await page.locator(`.react-flow__node[data-id="${map.nodeId}"]`).click(); await expect(page.getByLabel('学習項目名（必須）', { exact: true })).toHaveValue('選択中の項目A');
  const input = page.getByLabel(kind === 'map' ? 'マップ名（必須）' : '学習目標（任意・1行1項目）'); const desired = '人間が最初に保存する内容'; const later = '結果不明後に人間が編集した内容'; const other = '別の画面で保存した現在内容'; await input.fill(desired); let patches = 0;
  const path = kind === 'map' ? `/api/roadmaps/${map.id}` : `/api/nodes/${map.nodeId}`; await page.route(`**${path}?*`, async (route) => { if (route.request().method() !== 'PATCH') return route.continue(); patches++; const response = await route.fetch(); expect(response.status()).toBe(200); if (patches === 1) return route.abort(); return route.fulfill({ response }); });
  const save = page.getByRole('button', { name: kind === 'map' ? 'マップを保存' : '学習項目を保存', exact: true }); await save.click(); const recovery = page.getByRole('region', { name: 'マップ・項目の保存結果の確認', exact: true }); await expect(recovery).toBeVisible(); await expect(save).toBeDisabled(); await expect(page.locator(kind === 'map' ? '.map-toolbar' : '.node-details')).not.toContainText('保存に失敗しました'); await expect(input).toBeEnabled(); await input.fill(later);
  await page.getByLabel('考えるための問い（任意・1行1項目）').fill('人間の未保存の問い'); await page.getByLabel('資料URL（必須）').fill('https://example.com/graph-save-draft'); await page.getByLabel('資料名（任意）').fill('人間の未登録資料'); await page.getByLabel('新しい学習項目（必須）').fill('人間の次の項目名');
  if (current === 'different') expect((await request.patch(path, { data: kind === 'map' ? { title: other } : { learningObjectives: [other] } })).status()).toBe(200);
  const viewport = await page.locator('.react-flow__viewport').getAttribute('style'); await recovery.getByRole('button', { name: '現在の保存済み内容を確認', exact: true }).click(); await expect(recovery.getByRole('region', { name: '確認した保存済み内容', exact: true })).toContainText(current === 'same' ? desired : other); await expect(save).toBeDisabled(); await expect(input).toHaveValue(later); await expect(page.getByLabel('考えるための問い（任意・1行1項目）')).toHaveValue('人間の未保存の問い'); await expect(page.getByLabel('資料名（任意）')).toHaveValue('人間の未登録資料'); await expect(page.getByLabel('新しい学習項目（必須）')).toHaveValue('人間の次の項目名'); await expect(page.getByLabel('学習項目名（必須）', { exact: true })).toHaveValue('選択中の項目A'); expect(await page.locator('.react-flow__viewport').getAttribute('style')).toBe(viewport); expect(patches).toBe(1);
  page.once('dialog', (dialog) => dialog.dismiss()); await page.getByRole('link', { name: 'ホーム', exact: true }).click(); await expect(page).toHaveURL(new RegExp(`/roadmaps/${map.id}$`)); const allow = recovery.getByRole('button', { name: '保存済み内容を確認しました。保存を再開', exact: true }); page.once('dialog', (dialog) => dialog.dismiss()); await allow.click(); await expect(recovery).toBeVisible(); page.once('dialog', (dialog) => dialog.accept()); await allow.click(); await expect(recovery).toHaveCount(0); expect(patches).toBe(1);
  await save.click(); await expect(page.locator(kind === 'map' ? '.map-toolbar' : '.node-details').getByText('保存しました', { exact: true })).toBeVisible(); expect(patches).toBe(2); const final = await (await request.get(`/api/roadmaps/${map.id}`)).json(); expect(kind === 'map' ? final.roadmap.title : final.nodes[0].learningObjectives[0]).toBe(later); await expect(page.getByLabel('資料名（任意）')).toHaveValue('人間の未登録資料'); await expect(page.getByLabel('新しい学習項目（必須）')).toHaveValue('人間の次の項目名');
});

for (const kind of ['map','node'] as const) for (const loss of ['json','server'] as const) test(`${kind} committed ${loss} reply stays unknown and cannot normally resend`, async ({ page, map }) => {
  await page.goto(`/workspaces/default/roadmaps/${map.id}`); if (kind === 'node') await page.locator(`.react-flow__node[data-id="${map.nodeId}"]`).click(); await page.getByLabel(kind === 'map' ? 'マップ名（必須）' : '学習目標（任意・1行1項目）').fill('実保存される内容'); let patches = 0; const path = kind === 'map' ? `/api/roadmaps/${map.id}` : `/api/nodes/${map.nodeId}`;
  await page.route(`**${path}?*`, async (route) => { if (route.request().method() !== 'PATCH') return route.continue(); patches++; const response = await route.fetch(); expect(response.status()).toBe(200); return route.fulfill(loss === 'server' ? { status: 503, json: { secret: 'internal' } } : { status: 200, contentType: 'application/json', body: 'internal' }); }); const save = page.getByRole('button', { name: kind === 'map' ? 'マップを保存' : '学習項目を保存', exact: true }); await save.click(); await expect(page.getByRole('region', { name: 'マップ・項目の保存結果の確認', exact: true })).toBeVisible(); await expect(save).toBeDisabled(); expect(patches).toBe(1); await expect(page.locator('body')).not.toContainText('internal');
});

test('failed, foreign and missing-target reads never permit save recovery acknowledgment', async ({ page, map }) => {
  await page.goto(`/workspaces/default/roadmaps/${map.id}`); await page.locator(`.react-flow__node[data-id="${map.nodeId}"]`).click(); await page.getByLabel('学習目標（任意・1行1項目）').fill('人間の保存要求'); await page.route(`**/api/nodes/${map.nodeId}?*`, (route) => route.abort()); await page.getByRole('button', { name: '学習項目を保存', exact: true }).click(); const recovery = page.getByRole('region', { name: 'マップ・項目の保存結果の確認', exact: true }); await expect(recovery).toBeVisible();
  for (const kind of ['failed','foreign','missing']) { await page.route(`**/api/roadmaps/${map.id}?*`, async (route) => { if (kind === 'failed') return route.fulfill({ status: 503, json: { secret: 'internal' } }); const response = await route.fetch(); const payload = await response.json(); if (kind === 'foreign') payload.roadmap.id = 'other'; else payload.nodes = []; return route.fulfill({ response, json: payload }); }); await recovery.getByRole('button', { name: '現在の保存済み内容を確認', exact: true }).click(); await expect(recovery).toContainText('保存済み内容を取得できませんでした'); await expect(recovery.getByRole('button', { name: '保存済み内容を確認しました。保存を再開', exact: true })).toHaveCount(0); await page.unroute(`**/api/roadmaps/${map.id}?*`); }
  await recovery.getByRole('button', { name: '現在の保存済み内容を確認', exact: true }).click(); await expect(recovery.getByRole('region', { name: '確認した保存済み内容', exact: true })).toContainText('初期目標'); await expect(page.getByRole('button', { name: '学習項目を保存', exact: true })).toBeDisabled(); await expect(page.getByLabel('学習目標（任意・1行1項目）')).toHaveValue('人間の保存要求');
});

for (const kind of ['map','node'] as const) test(`known ${kind} rejection retains safe error and normal retry`, async ({ page, request, map }) => {
  await page.goto(`/workspaces/default/roadmaps/${map.id}`); if (kind === 'node') await page.locator(`.react-flow__node[data-id="${map.nodeId}"]`).click(); const input = page.getByLabel(kind === 'map' ? 'マップ名（必須）' : '学習目標（任意・1行1項目）'); await input.fill('既知の拒否の入力'); const path = kind === 'map' ? `/api/roadmaps/${map.id}` : `/api/nodes/${map.nodeId}`; await page.route(`**${path}?*`, (route) => route.request().method() === 'PATCH' ? route.fulfill({ status: 403, json: { secret: 'internal' } }) : route.continue()); const save = page.getByRole('button', { name: kind === 'map' ? 'マップを保存' : '学習項目を保存', exact: true }); await save.click(); await expect(page.getByRole('alert')).toContainText('この操作は許可されていません'); await expect(save).toBeEnabled(); await expect(input).toHaveValue('既知の拒否の入力'); await expect(page.getByRole('region', { name: 'マップ・項目の保存結果の確認', exact: true })).toHaveCount(0); const saved = await (await request.get(`/api/roadmaps/${map.id}`)).json(); expect(saved.roadmap.title).toBe(map.title); expect(saved.nodes[0].learningObjectives).toEqual(['初期目標']);
});

for (const kind of ['map','node'] as const) test(`confirmed ${kind} PATCH with failed postwrite GET remains confirmed`, async ({ page, request, map }) => {
  await page.goto(`/workspaces/default/roadmaps/${map.id}`); if (kind === 'node') await page.locator(`.react-flow__node[data-id="${map.nodeId}"]`).click(); await page.getByLabel(kind === 'map' ? 'マップ名（必須）' : '学習目標（任意・1行1項目）').fill('確定した保存内容'); let committed = false; let patches = 0; let reads = 0;
  const path = kind === 'map' ? `/api/roadmaps/${map.id}` : `/api/nodes/${map.nodeId}`; await page.route(`**${path}?*`, async (route) => { if (route.request().method() !== 'PATCH') return route.continue(); patches++; const response = await route.fetch(); committed = true; return route.fulfill({ response }); }); await page.route(`**/api/roadmaps/${map.id}?*`, async (route) => { if (route.request().method() !== 'GET') return route.fallback(); if (committed && ++reads <= 2) return route.abort(); return route.continue(); });
  await page.getByRole('button', { name: kind === 'map' ? 'マップを保存' : '学習項目を保存', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('変更は保存されましたが'); await expect(page.locator(kind === 'map' ? '.map-toolbar' : '.node-details').getByText('保存しました', { exact: true })).toBeVisible(); await expect(page.getByRole('region', { name: 'マップ・項目の保存結果の確認', exact: true })).toHaveCount(0); await page.getByRole('button', { name: '最新の表示を再取得', exact: true }).click(); await expect(page.getByRole('alert')).toHaveCount(0); expect(patches).toBe(1); const saved = await (await request.get(`/api/roadmaps/${map.id}`)).json(); expect(kind === 'map' ? saved.roadmap.title : saved.nodes[0].learningObjectives[0]).toBe('確定した保存内容');
});

test('late successful save response from prior map cannot change a new maps unknown result', async ({ page, request, map }) => {
  const { roadmap: other } = await (await request.post('/api/roadmaps', { data: { title: '後の保存先' } })).json(); let release!: () => void; let reached!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const started = new Promise<void>((resolve) => { reached = resolve; });
  try { await page.goto(`/workspaces/default/roadmaps/${map.id}`); await page.getByLabel('マップ名（必須）').fill('前の地図の送信'); await page.route(`**/api/roadmaps/${map.id}?*`, async (route) => { if (route.request().method() !== 'PATCH') return route.continue(); const response = await route.fetch(); reached(); await gate; return route.fulfill({ response }); }); await page.getByRole('button', { name: 'マップを保存', exact: true }).click(); await started; page.once('dialog', (dialog) => dialog.accept()); await page.getByRole('link', { name: other.title, exact: true }).click(); await page.getByLabel('マップ名（必須）').fill('後の地図の保存要求'); await page.route(`**/api/roadmaps/${other.id}?*`, (route) => route.request().method() === 'PATCH' ? route.abort() : route.continue()); await page.getByRole('button', { name: 'マップを保存', exact: true }).click(); const recovery = page.getByRole('region', { name: 'マップ・項目の保存結果の確認', exact: true }); await expect(recovery).toContainText(other.title); release(); await page.unrouteAll({ behavior: 'wait' }); await expect(recovery).toContainText(other.title); await expect(page.getByLabel('マップ名（必須）')).toHaveValue('後の地図の保存要求'); await expect(page.getByRole('button', { name: 'マップを保存', exact: true })).toBeDisabled(); } finally { release(); await page.unrouteAll({ behavior: 'wait' }); await request.delete(`/api/roadmaps/${other.id}`); }
});

test('old confirmation GET cannot provide a current state for a later maps unknown save', async ({ page, request, map }) => {
  const { roadmap: other } = await (await request.post('/api/roadmaps', { data: { title: '後の確認先' } })).json(); let release!: () => void; let reached!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const started = new Promise<void>((resolve) => { reached = resolve; });
  try { await page.goto(`/workspaces/default/roadmaps/${map.id}`); await page.getByLabel('マップ名（必須）').fill('前の不明な保存'); await page.route(`**/api/roadmaps/${map.id}?*`, (route) => route.request().method() === 'PATCH' ? route.abort() : route.continue()); await page.getByRole('button', { name: 'マップを保存', exact: true }).click(); const recovery = page.getByRole('region', { name: 'マップ・項目の保存結果の確認', exact: true }); await expect(recovery).toBeVisible(); await page.route(`**/api/roadmaps/${map.id}?*`, async (route) => { const response = await route.fetch(); reached(); await gate; return route.fulfill({ response }); }); await recovery.getByRole('button', { name: '現在の保存済み内容を確認', exact: true }).click(); await started; page.once('dialog', (dialog) => dialog.accept()); await page.getByRole('link', { name: other.title, exact: true }).click(); await page.getByLabel('マップ名（必須）').fill('後の不明な保存'); await page.route(`**/api/roadmaps/${other.id}?*`, (route) => route.request().method() === 'PATCH' ? route.abort() : route.continue()); await page.getByRole('button', { name: 'マップを保存', exact: true }).click(); await expect(recovery).toContainText(other.title); release(); await page.unrouteAll({ behavior: 'wait' }); await expect(recovery.getByRole('region', { name: '確認した保存済み内容', exact: true })).toHaveCount(0); await expect(recovery.getByRole('button', { name: '保存済み内容を確認しました。保存を再開', exact: true })).toHaveCount(0); await expect(page.getByLabel('マップ名（必須）')).toHaveValue('後の不明な保存'); } finally { release(); await page.unrouteAll({ behavior: 'wait' }); await request.delete(`/api/roadmaps/${other.id}`); }
});

for (const kind of ['map','node'] as const) test(`synchronous ${kind} save submissions send one PATCH`, async ({ page, request, map }) => {
  let patches = 0; let release!: () => void; let reached!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const started = new Promise<void>((resolve) => { reached = resolve; }); const path = kind === 'map' ? `/api/roadmaps/${map.id}` : `/api/nodes/${map.nodeId}`;
  try { await page.goto(`/workspaces/default/roadmaps/${map.id}`); if (kind === 'node') await page.locator(`.react-flow__node[data-id="${map.nodeId}"]`).click(); await page.getByLabel(kind === 'map' ? 'マップ名（必須）' : '学習目標（任意・1行1項目）').fill('同期保存は一つ'); await page.route(`**${path}?*`, async (route) => { if (route.request().method() !== 'PATCH') return route.continue(); patches++; const response = await route.fetch(); reached(); await gate; return route.fulfill({ response }); }); await page.locator(kind === 'map' ? 'form.map-toolbar' : '.node-details > form').evaluate((form: HTMLFormElement) => { for (let i = 0; i < 3; i++) form.requestSubmit(); }); await started; release(); await expect(page.locator(kind === 'map' ? '.map-toolbar' : '.node-details').getByText('保存しました', { exact: true })).toBeVisible(); expect(patches).toBe(1); const saved = await (await request.get(`/api/roadmaps/${map.id}`)).json(); expect(kind === 'map' ? saved.roadmap.title : saved.nodes[0].learningObjectives[0]).toBe('同期保存は一つ'); } finally { release(); await page.unrouteAll({ behavior: 'wait' }); }
});

test('node creation and graph save uncertainty keep independent acknowledgment and input', async ({ page, map }) => {
  let posts = 0; let patches = 0; await page.goto(`/workspaces/default/roadmaps/${map.id}`); await page.getByLabel('新しい学習項目（必須）').fill('作成不明の入力'); await page.route('**/api/nodes?*', (route) => { posts++; return route.abort(); }); await page.getByRole('button', { name: '学習項目を追加', exact: true }).click(); const creation = page.getByRole('region', { name: '学習項目の作成結果の確認', exact: true }); await expect(creation).toBeVisible(); await page.getByLabel('マップ名（必須）').fill('保存不明の入力'); await page.route(`**/api/roadmaps/${map.id}?*`, (route) => { if (route.request().method() !== 'PATCH') return route.continue(); patches++; return route.abort(); }); await page.getByRole('button', { name: 'マップを保存', exact: true }).click(); const save = page.getByRole('region', { name: 'マップ・項目の保存結果の確認', exact: true }); await expect(save).toBeVisible();
  await save.getByRole('button', { name: '現在の保存済み内容を確認', exact: true }).click(); page.once('dialog', (dialog) => dialog.accept()); await save.getByRole('button', { name: '保存済み内容を確認しました。保存を再開', exact: true }).click(); await expect(save).toHaveCount(0); await expect(creation).toBeVisible(); await expect(page.getByRole('button', { name: '学習項目を追加', exact: true })).toBeDisabled(); await expect(page.getByRole('button', { name: 'マップを保存', exact: true })).toBeEnabled(); expect(posts).toBe(1); expect(patches).toBe(1); await expect(page.getByLabel('マップ名（必須）')).toHaveValue('保存不明の入力');
  await creation.getByRole('button', { name: '作成済みの学習項目を確認', exact: true }).click(); page.once('dialog', (dialog) => dialog.accept()); await creation.getByRole('button', { name: '一覧を確認しました。新しく作成', exact: true }).click(); await expect(creation).toHaveCount(0); await expect(page.getByLabel('新しい学習項目（必須）')).toHaveValue('作成不明の入力'); expect(posts).toBe(1); expect(patches).toBe(1);
});
