import { test as base, expect } from '@playwright/test';

type Fixture = { id: string; nodeId: string; title: string };
const test = base.extend<{ map: Fixture }>({ map: async ({ request }, use) => {
  const { roadmap } = await (await request.post('/api/roadmaps', { data: { title: '人間の元の地図名A' } })).json(); const { node } = await (await request.post('/api/nodes', { data: { roadmapId: roadmap.id, title: '人間の選択項目', learningObjectives: ['人間の元の目標A'] } })).json();
  try { await use({ id: roadmap.id, nodeId: node.id, title: roadmap.title }); } finally { await request.delete(`/api/roadmaps/${roadmap.id}`); }
} });

for (const kind of ['map', 'node'] as const) for (const operation of ['node create', 'resource link', 'node candidate read'] as const) test(`${kind} ABA input survives ${operation} refresh and acknowledgment until explicit confirmed save`, async ({ page, request, map }) => {
  await page.goto(`/workspaces/default/roadmaps/${map.id}`); await page.locator(`.react-flow__node[data-id="${map.nodeId}"]`).click(); const input = page.getByLabel(kind === 'map' ? 'マップ名（必須）' : '学習目標（任意・1行1項目）'); const original = await input.inputValue(); await input.fill('実際に保存したB'); let patches = 0;
  const path = kind === 'map' ? `/api/roadmaps/${map.id}` : `/api/nodes/${map.nodeId}`; await page.route(`**${path}?*`, async route => { if (route.request().method() !== 'PATCH') return route.continue(); patches++; const response = await route.fetch(); expect(response.status()).toBe(200); if (patches === 1) return route.abort(); return route.fulfill({ response }); }); await page.getByRole('button', { name: kind === 'map' ? 'マップを保存' : '学習項目を保存', exact: true }).click(); const recovery = page.getByRole('region', { name: 'マップ・項目の保存結果の確認', exact: true }); await expect(recovery).toBeVisible(); await input.fill(original);
  const draft = page.locator(kind === 'map' ? '.map-toolbar' : '.node-details > form'); await expect(draft.getByText('未保存の変更', { exact: true })).toBeVisible();
  const viewport = await page.locator('.react-flow__viewport').getAttribute('style');
  if (operation === 'resource link') { await page.getByLabel('登録済み資料').selectOption({ label: 'RFC 6749' }); await page.getByRole('button', { name: '資料を関連付け', exact: true }).click(); await expect(page.getByRole('button', { name: '関連を外す', exact: true })).toHaveCount(1); }
  else {
    if (operation === 'node candidate read') await page.route('**/api/nodes?*', async route => { const response = await route.fetch(); expect(response.status()).toBe(201); return route.abort(); });
    await page.getByLabel('新しい学習項目（必須）').fill('人間が追加する別項目'); await page.getByRole('button', { name: '学習項目を追加', exact: true }).click();
    if (operation === 'node candidate read') { const creation = page.getByRole('region', { name: '学習項目の作成結果の確認', exact: true }); await expect(creation).toBeVisible(); await creation.getByRole('button', { name: '作成済みの学習項目を確認', exact: true }).click(); await expect(creation.getByRole('listitem')).toHaveCount(1); }
    await expect(page.locator('.react-flow__node')).toHaveCount(2);
  }
  await expect(page.locator('.map-layout')).toHaveAttribute('aria-busy', 'false'); await expect(input).toHaveValue(original); if (kind === 'node') await expect(page.getByLabel('学習項目名（必須）', { exact: true })).toHaveValue('人間の選択項目'); expect(await page.locator('.react-flow__viewport').getAttribute('style')).toBe(viewport); expect(patches).toBe(1);
  await recovery.getByRole('button', { name: '現在の保存済み内容を確認', exact: true }).click(); await expect(recovery.getByRole('region', { name: '確認した保存済み内容', exact: true })).toContainText('実際に保存したB'); page.once('dialog', dialog => dialog.accept()); await recovery.getByRole('button', { name: '保存済み内容を確認しました。保存を再開', exact: true }).click(); expect(patches).toBe(1); await expect(input).toHaveValue(original); await expect(draft.getByText('未保存の変更', { exact: true })).toBeVisible();
  if (operation === 'node candidate read') { const creation = page.getByRole('region', { name: '学習項目の作成結果の確認', exact: true }); page.once('dialog', dialog => dialog.accept()); await creation.getByRole('button', { name: '一覧を確認しました。新しく作成', exact: true }).click(); await page.unroute('**/api/nodes?*'); }
  await page.getByLabel('新しい学習項目（必須）').fill('了承後に追加する別項目'); await page.getByRole('button', { name: '学習項目を追加', exact: true }).click(); await expect(page.locator('.react-flow__node')).toHaveCount(operation === 'resource link' ? 2 : 3); await expect(page.locator('.map-layout')).toHaveAttribute('aria-busy', 'false'); await expect(input).toHaveValue(original); if (kind === 'node') await expect(page.getByLabel('学習項目名（必須）', { exact: true })).toHaveValue('人間の選択項目');
  await page.getByRole('button', { name: kind === 'map' ? 'マップを保存' : '学習項目を保存', exact: true }).click(); await expect(draft.getByText('保存しました', { exact: true })).toBeVisible(); expect(patches).toBe(2); const current = await (await request.get(`/api/roadmaps/${map.id}`)).json(); expect(kind === 'map' ? current.roadmap.title : current.nodes.find((n: { id: string }) => n.id === map.nodeId).learningObjectives[0]).toBe(original); await expect(draft.getByText('未保存の変更', { exact: true })).toHaveCount(0);
  await input.fill('確定保存後の一時編集'); await input.fill(original); await expect(draft.getByText('未保存の変更', { exact: true })).toHaveCount(0);
});

test('node ABA intent still asks before selecting another node while its save is unknown', async ({ page, request, map }) => {
  const { node: other } = await (await request.post('/api/nodes', { data: { roadmapId: map.id, title: '移動先', positionX: 320 } })).json(); await page.goto(`/workspaces/default/roadmaps/${map.id}`); await page.locator(`.react-flow__node[data-id="${map.nodeId}"]`).click(); const input = page.getByLabel('学習目標（任意・1行1項目）'); const original = await input.inputValue(); await input.fill('実保存B'); await page.route(`**/api/nodes/${map.nodeId}?*`, async route => { await route.fetch(); return route.abort(); }); await page.getByRole('button', { name: '学習項目を保存', exact: true }).click(); await expect(page.getByRole('region', { name: 'マップ・項目の保存結果の確認', exact: true })).toBeVisible(); await input.fill(original);
  let dialogs = 0; page.on('dialog', async dialog => { dialogs++; await dialog.dismiss(); }); await page.locator(`.react-flow__node[data-id="${other.id}"]`).focus(); await page.keyboard.press('Enter'); expect(dialogs).toBe(1); await expect(page.getByLabel('学習項目名（必須）', { exact: true })).toHaveValue('人間の選択項目'); await expect(input).toHaveValue(original);
});

test('confirmed position-only write cannot release node ABA preservation after an unknown full save', async ({ page, request, map }) => {
  await page.goto(`/workspaces/default/roadmaps/${map.id}`); const node = page.locator(`.react-flow__node[data-id="${map.nodeId}"]`); await node.click(); const input = page.getByLabel('学習目標（任意・1行1項目）'); const original = await input.inputValue(); await input.fill('実保存B'); let patches = 0;
  await page.route(`**/api/nodes/${map.nodeId}?*`, async route => { if (route.request().method() !== 'PATCH') return route.continue(); patches++; const response = await route.fetch(); expect(response.status()).toBe(200); return patches === 1 ? route.abort() : route.fulfill({ response }); }); await page.getByRole('button', { name: '学習項目を保存', exact: true }).click(); const recovery = page.getByRole('region', { name: 'マップ・項目の保存結果の確認', exact: true }); await expect(recovery).toBeVisible(); await input.fill(original);
  await node.focus(); await page.keyboard.press('ArrowRight'); await expect(page.getByLabel('X', { exact: true })).not.toHaveValue('0'); await expect(page.locator('.map-layout')).toHaveAttribute('aria-busy', 'false'); expect(patches).toBe(2); await expect(input).toHaveValue(original); await expect(page.locator('.node-details > form').getByText('未保存の変更', { exact: true })).toBeVisible(); await expect(recovery).toBeVisible(); await expect(page.getByRole('button', { name: '学習項目を保存', exact: true })).toBeDisabled();
  const current = await (await request.get(`/api/roadmaps/${map.id}`)).json(); expect(current.nodes[0].learningObjectives).toEqual(['実保存B']); expect(current.nodes[0].positionX).toBe(Number(await page.getByLabel('X', { exact: true }).inputValue()));
  await recovery.getByRole('button', { name: '現在の保存済み内容を確認', exact: true }).click(); page.once('dialog', dialog => dialog.accept()); await recovery.getByRole('button', { name: '保存済み内容を確認しました。保存を再開', exact: true }).click(); expect(patches).toBe(2); await page.getByRole('button', { name: '学習項目を保存', exact: true }).click(); await expect(page.locator('.node-details > form').getByText('保存しました', { exact: true })).toBeVisible(); expect(patches).toBe(3); expect((await (await request.get(`/api/roadmaps/${map.id}`)).json()).nodes[0].learningObjectives).toEqual([original]);
});
