import { test as base, expect } from './manual-note-fixture';

type MapFixture = { id: string; nodeId: string; title: string };
const test = base.extend<{ map: MapFixture }>({ map: async ({ request }, use) => {
  const { roadmap } = await (await request.post('/api/roadmaps', { data: { title: '作成回復と人間の入力' } })).json();
  const { node } = await (await request.post('/api/nodes', { data: { roadmapId: roadmap.id, title: '選択中の項目', learningObjectives: ['保存済みの目標'] } })).json();
  try { await use({ id: roadmap.id, nodeId: node.id, title: roadmap.title }); } finally { await request.delete(`/api/roadmaps/${roadmap.id}`); }
} });

for (const loss of ['transport', 'json', 'target'] as const) test(`committed node ${loss} response needs explicit read and acknowledgment, keeping all human inputs`, async ({ page, request, map }) => {
  await page.setViewportSize({ width: 390, height: 844 }); let posts = 0;
  await page.goto(`/workspaces/default/roadmaps/${map.id}`); await page.locator(`.react-flow__node[data-id="${map.nodeId}"]`).click(); await expect(page.getByLabel('学習項目名（必須）', { exact: true })).toHaveValue('選択中の項目'); await page.getByLabel('学習目標（任意・1行1項目）').fill('人間が編集中の目標'); await page.getByLabel('考えるための問い（任意・1行1項目）').fill('人間が編集中の問い'); await page.getByLabel('マップ名（必須）').fill('人間が編集中の地図名'); await page.getByLabel('資料URL（必須）').fill('https://example.com/my-resource'); await page.getByLabel('資料名（任意）').fill('人間の未登録資料');
  const input = page.getByLabel('新しい学習項目（必須）'); const submitted = '新しい人間の項目'; await input.fill(submitted);
  await page.route('**/api/nodes?*', async (route) => { if (route.request().method() !== 'POST') return route.continue(); posts++; const response = await route.fetch(); expect(response.status()).toBe(201); if (posts > 1) return route.fulfill({ response }); if (loss === 'transport') return route.abort(); if (loss === 'json') return route.fulfill({ status: 201, contentType: 'application/json', body: 'invalid-private-json' }); const payload = await response.json(); payload.node.roadmapId = 'other'; return route.fulfill({ response, json: payload }); });
  const add = page.getByRole('button', { name: '学習項目を追加', exact: true }); await add.click(); const recovery = page.getByRole('region', { name: '学習項目の作成結果の確認', exact: true }); await expect(recovery).toBeVisible(); await expect(add).toBeDisabled(); await expect(input).toHaveValue(submitted); await input.press('Enter'); expect(posts).toBe(1);
  await recovery.getByRole('button', { name: '作成済みの学習項目を確認', exact: true }).click(); await expect(recovery.getByRole('listitem')).toHaveCount(1); await expect(recovery.getByRole('listitem')).toHaveText(submitted); await expect(add).toBeDisabled(); expect(posts).toBe(1);
  await expect(page.getByLabel('学習項目名（必須）', { exact: true })).toHaveValue('選択中の項目'); await expect(page.getByLabel('学習目標（任意・1行1項目）')).toHaveValue('人間が編集中の目標'); await expect(page.getByLabel('考えるための問い（任意・1行1項目）')).toHaveValue('人間が編集中の問い'); await expect(page.getByLabel('マップ名（必須）')).toHaveValue('人間が編集中の地図名'); await expect(page.getByLabel('資料名（任意）')).toHaveValue('人間の未登録資料');
  page.once('dialog', (dialog) => dialog.dismiss()); await page.getByRole('link', { name: 'ホーム', exact: true }).click(); await expect(page).toHaveURL(new RegExp(`/roadmaps/${map.id}$`)); const allow = recovery.getByRole('button', { name: '一覧を確認しました。新しく作成', exact: true }); page.once('dialog', (dialog) => dialog.dismiss()); await allow.click(); await expect(recovery).toBeVisible(); page.once('dialog', (dialog) => dialog.accept()); await allow.click(); await expect(recovery).toHaveCount(0); expect(posts).toBe(1);
  await input.fill('明示的に別の項目を作る'); await add.click(); await expect(input).toHaveValue(''); await expect(page.locator('.map-layout')).toHaveAttribute('aria-busy', 'false'); const detail = await (await request.get(`/api/roadmaps/${map.id}`)).json(); expect(detail.nodes).toHaveLength(3); expect(posts).toBe(2); expect(detail.roadmap.title).toBe(map.title); expect(detail.nodes.find((node: { id: string }) => node.id === map.nodeId).learningObjectives).toEqual(['保存済みの目標']); await expect(page.getByLabel('学習目標（任意・1行1項目）')).toHaveValue('人間が編集中の目標');
});

test('confirmed node response clears only its submitted name and retains the next human input and departure guard', async ({ page, request, map }) => {
  let release!: () => void; let reached!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const started = new Promise<void>((resolve) => { reached = resolve; });
  await page.goto(`/workspaces/default/roadmaps/${map.id}`); const input = page.getByLabel('新しい学習項目（必須）'); await input.fill('最初の送信名'); await page.route('**/api/nodes?*', async (route) => { const response = await route.fetch(); expect(response.status()).toBe(201); reached(); await gate; return route.fulfill({ response }); });
  try {
    await page.getByRole('button', { name: '学習項目を追加', exact: true }).click(); await started; await input.fill('返答を待つ間に人間が考えた次の項目'); release(); await expect(page.locator('.map-layout')).toHaveAttribute('aria-busy', 'false'); await expect(input).toHaveValue('返答を待つ間に人間が考えた次の項目'); await expect(page.getByRole('region', { name: '学習項目の作成結果の確認', exact: true })).toHaveCount(0); expect((await (await request.get(`/api/roadmaps/${map.id}`)).json()).nodes).toHaveLength(2); let warned = false; page.once('dialog', async (dialog) => { warned = true; await dialog.dismiss(); }); await page.getByRole('link', { name: 'ホーム', exact: true }).click(); expect(warned).toBe(true); await expect(page).toHaveURL(new RegExp(`/roadmaps/${map.id}$`));
  } finally { release(); await page.unrouteAll({ behavior: 'wait' }); }
});

test('failed or wrong-map reads and an empty list preserve node creation uncertainty', async ({ page, map }) => {
  await page.goto(`/workspaces/default/roadmaps/${map.id}`); await page.getByLabel('新しい学習項目（必須）').fill('まだ確認できない項目'); await page.route('**/api/nodes?*', (route) => route.abort()); await page.getByRole('button', { name: '学習項目を追加', exact: true }).click(); const recovery = page.getByRole('region', { name: '学習項目の作成結果の確認', exact: true }); await expect(recovery).toBeVisible();
  for (const kind of ['failed', 'wrong-map']) {
    await page.route(`**/api/roadmaps/${map.id}?*`, async (route) => { if (kind === 'failed') return route.fulfill({ status: 503, json: { secret: 'internal' } }); const response = await route.fetch(); const payload = await response.json(); payload.roadmap.id = 'other'; return route.fulfill({ response, json: payload }); });
    await recovery.getByRole('button', { name: '作成済みの学習項目を確認', exact: true }).click(); await expect(recovery).toContainText('一覧を取得できませんでした'); await expect(recovery.getByRole('button', { name: '一覧を確認しました。新しく作成', exact: true })).toHaveCount(0); await page.unroute(`**/api/roadmaps/${map.id}?*`);
  }
  await recovery.getByRole('button', { name: '作成済みの学習項目を確認', exact: true }).click(); await expect(recovery.getByRole('listitem')).toHaveCount(0); await expect(recovery.getByRole('button', { name: '一覧を確認しました。新しく作成', exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: '学習項目を追加', exact: true })).toBeDisabled();
});

test('known creation rejection retains the input and retry without unknown result', async ({ page, request, map }) => {
  await page.goto(`/workspaces/default/roadmaps/${map.id}`); const input = page.getByLabel('新しい学習項目（必須）'); await input.fill('拒否された入力を保持'); await page.route('**/api/nodes?*', (route) => route.fulfill({ status: 400, json: { secret: 'private' } })); const add = page.getByRole('button', { name: '学習項目を追加', exact: true }); await add.click(); await expect(page.getByRole('alert')).toContainText('入力内容を確認して再試行'); await expect(add).toBeEnabled(); await expect(input).toHaveValue('拒否された入力を保持'); await expect(page.getByRole('region', { name: '学習項目の作成結果の確認', exact: true })).toHaveCount(0); expect((await (await request.get(`/api/roadmaps/${map.id}`)).json()).nodes).toHaveLength(1);
});

test('old creation response cannot clear the next maps human input or unknown result', async ({ page, request, map }) => {
  const { roadmap: other } = await (await request.post('/api/roadmaps', { data: { title: '次の地図' } })).json(); let release!: () => void; let reached!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const started = new Promise<void>((resolve) => { reached = resolve; }); let posts = 0;
  await page.route('**/api/nodes?*', async (route) => { posts++; if (posts > 1) return route.abort(); const response = await route.fetch(); reached(); await gate; return route.fulfill({ response }); });
  try {
    await page.goto(`/workspaces/default/roadmaps/${map.id}`); const input = page.getByLabel('新しい学習項目（必須）'); await input.fill('前の地図の作成'); await page.getByRole('button', { name: '学習項目を追加', exact: true }).click(); await started; page.once('dialog', (dialog) => dialog.accept()); await page.getByRole('link', { name: '次の地図', exact: true }).click(); await expect(page).toHaveURL(new RegExp(`/roadmaps/${other.id}$`)); await input.fill('次の地図の人間入力'); await page.getByRole('button', { name: '学習項目を追加', exact: true }).click(); const recovery = page.getByRole('region', { name: '学習項目の作成結果の確認', exact: true }); await expect(recovery).toBeVisible(); release(); await page.unrouteAll({ behavior: 'wait' }); await expect(recovery).toContainText('次の地図の人間入力'); await expect(input).toHaveValue('次の地図の人間入力'); await expect(page.getByRole('button', { name: '学習項目を追加', exact: true })).toBeDisabled(); expect((await (await request.get(`/api/roadmaps/${other.id}`)).json()).nodes).toHaveLength(0);
  } finally { release(); await page.unrouteAll({ behavior: 'wait' }); await request.delete(`/api/roadmaps/${other.id}`); }
});

test('old creation confirmation GET cannot change the next maps unknown candidates or graph', async ({ page, request, map }) => {
  const { roadmap: other } = await (await request.post('/api/roadmaps', { data: { title: '別の地図の確認先' } })).json(); let release!: () => void; let reached!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const started = new Promise<void>((resolve) => { reached = resolve; });
  try {
    await page.route('**/api/nodes?*', (route) => route.abort()); await page.goto(`/workspaces/default/roadmaps/${map.id}`); const input = page.getByLabel('新しい学習項目（必須）'); await input.fill('前の結果不明'); await page.getByRole('button', { name: '学習項目を追加', exact: true }).click(); const recovery = page.getByRole('region', { name: '学習項目の作成結果の確認', exact: true }); await expect(recovery).toBeVisible();
    await page.route(`**/api/roadmaps/${map.id}?*`, async (route) => { const response = await route.fetch(); reached(); await gate; return route.fulfill({ response }); }); await recovery.getByRole('button', { name: '作成済みの学習項目を確認', exact: true }).click(); await started; page.once('dialog', (dialog) => dialog.accept()); await page.getByRole('link', { name: '別の地図の確認先', exact: true }).click(); await input.fill('別の地図の新しい不明'); await page.getByRole('button', { name: '学習項目を追加', exact: true }).click(); await expect(recovery).toBeVisible(); release(); await page.unrouteAll({ behavior: 'wait' }); await expect(recovery).toContainText('別の地図の新しい不明'); await expect(recovery.getByRole('button', { name: '一覧を確認しました。新しく作成', exact: true })).toHaveCount(0); await expect(page.getByLabel('マップ名（必須）')).toHaveValue(other.title); await expect(page.locator('.react-flow__node')).toHaveCount(0);
  } finally { release(); await page.unrouteAll({ behavior: 'wait' }); await request.delete(`/api/roadmaps/${other.id}`); }
});

test('confirmed node creation plus failed refresh remains confirmed and does not clear the later input', async ({ page, request, map }) => {
  await page.goto(`/workspaces/default/roadmaps/${map.id}`); const input = page.getByLabel('新しい学習項目（必須）'); await input.fill('確定して作る項目'); let posts = 0; let committed = false; let reads = 0;
  await page.route('**/api/nodes?*', async (route) => { posts++; const response = await route.fetch(); committed = true; return route.fulfill({ response }); }); await page.route(`**/api/roadmaps/${map.id}?*`, (route) => { if (committed && ++reads <= 2) return route.abort(); return route.continue(); });
  await page.getByRole('button', { name: '学習項目を追加', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('変更は保存されましたが'); await expect(page.getByRole('region', { name: '学習項目の作成結果の確認', exact: true })).toHaveCount(0); await input.fill('次に人間が考えた項目'); await page.getByRole('button', { name: '最新の表示を再取得', exact: true }).click(); await expect(page.getByRole('alert')).toHaveCount(0); await expect(input).toHaveValue('次に人間が考えた項目'); expect(posts).toBe(1); expect((await (await request.get(`/api/roadmaps/${map.id}`)).json()).nodes).toHaveLength(2);
});

test('multiple same-name candidates and graph selection never release uncertain creation', async ({ page, request, map }) => {
  // Keep this candidate clear of the fixture's node at (0, 0) for a real pointer click.
  const title = '同じ名前の候補'; const { node: existing } = await (await request.post('/api/nodes', { data: { roadmapId: map.id, title, positionX: 320 } })).json(); await page.goto(`/workspaces/default/roadmaps/${map.id}`); await page.getByLabel('新しい学習項目（必須）').fill(title); let posts = 0;
  await page.route('**/api/nodes?*', async (route) => { posts++; await route.fetch(); return route.abort(); }); await page.getByRole('button', { name: '学習項目を追加', exact: true }).click(); const recovery = page.getByRole('region', { name: '学習項目の作成結果の確認', exact: true }); await expect(recovery).toBeVisible(); await recovery.getByRole('button', { name: '作成済みの学習項目を確認', exact: true }).click(); await expect(recovery.getByRole('listitem')).toHaveCount(2); await page.locator(`.react-flow__node[data-id="${existing.id}"]`).click(); await expect(page.getByLabel('学習項目名（必須）', { exact: true })).toHaveValue(title); await expect(recovery).toBeVisible(); await expect(page.getByRole('button', { name: '学習項目を追加', exact: true })).toBeDisabled(); expect(posts).toBe(1);
});

test('synchronous repeated node submissions send only one POST', async ({ page, request, map }) => {
  let posts = 0; let release!: () => void; let reached!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const started = new Promise<void>((resolve) => { reached = resolve; });
  await page.route('**/api/nodes?*', async (route) => { posts++; const response = await route.fetch(); reached(); await gate; return route.fulfill({ response }); });
  try { await page.goto(`/workspaces/default/roadmaps/${map.id}`); await page.getByLabel('新しい学習項目（必須）').fill('同期送信は一つ'); await page.locator('form.node-create').evaluate((form: HTMLFormElement) => { for (let index = 0; index < 3; index++) form.requestSubmit(); }); await started; release(); await expect(page.locator('.map-layout')).toHaveAttribute('aria-busy', 'false'); await expect(page.getByLabel('新しい学習項目（必須）')).toHaveValue(''); expect(posts).toBe(1); expect((await (await request.get(`/api/roadmaps/${map.id}`)).json()).nodes).toHaveLength(2); } finally { release(); await page.unrouteAll({ behavior: 'wait' }); }
});
