import { randomUUID } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { eq } from "drizzle-orm";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";
import { expect, it } from "vitest";
import { createDatabase } from "../../db/client";
import { readTestDatabaseUrl } from "../../lib/env";
import { workspaces, quotes, documentResources } from "../../db/schema";
import { backup, restore } from "../../modules/operations/backup";
import { LocalFileSystemStorage } from "../../modules/storage/local";
import { documentService } from "../../modules/document/service";
import { resourceService } from "../../modules/resource/service";
import { reviewService } from "../../modules/review/service";
import { mockProvider } from "../../modules/review/mock-provider";

it("restores DB, Markdown, revisions, quotes, resources and reviews as a pair without overwriting targets", async () => {
  const url = readTestDatabaseUrl();
  const admin = postgres(url, { max: 1, onnotice: () => {} });
  const targetName = `kakudo_restore_${randomUUID().replaceAll("-", "")}_test`;
  const target = new URL(url); target.pathname = `/${targetName}`;
  readTestDatabaseUrl({ TEST_DATABASE_URL: target.href, DATABASE_URL: url });
  const root = await mkdtemp(join(tmpdir(), "kakudo-backup-test-"));
  const { db, client } = createDatabase(url);
  const workspaceId = `backup-${randomUUID()}`;
  let restored: ReturnType<typeof createDatabase> | undefined;
  let created = false;
  try {
    await migrate(db, { migrationsFolder: "./db/migrations" });
    await db.insert(workspaces).values({ id: workspaceId, name: "Backup test" });
    const storage = new LocalFileSystemStorage(join(root, "original"));
    const docs = documentService(db, storage);
    const doc = await docs.create(workspaceId, { title: "My note", content: "My understanding.", nodeIds: [] });
    const original = await docs.get(doc.id, workspaceId);
    await docs.quote(doc.id, workspaceId, { title: "My note", content: original.content, baseHash: original.contentHash, from: original.content.length, to: original.content.length, text: "reference", sourceUrl: "https://example.com", sourceTitle: "Source" });
    const saved = await docs.get(doc.id, workspaceId);
    await resourceService(db).create(workspaceId, { url: "https://example.com", title: "Source", type: "WEB" }, { kind: "document", id: doc.id });
    const reviews = reviewService({ db, storage, provider: mockProvider() });
    const run = await reviews.start(doc.id, workspaceId, { revisionId: saved.document.currentRevisionId!, type: "LOGIC" }, false);
    await reviews.execute(run.id);
    const before = await reviews.get(run.id, workspaceId);
    const bundle = join(root, "bundle");
    await backup({ databaseUrl: url, storageRoot: join(root, "original"), destination: bundle });
    await expect(backup({ databaseUrl: url, storageRoot: join(root, "original"), destination: bundle })).rejects.toThrow();
    await admin.unsafe(`CREATE DATABASE "${targetName}"`); created = true;
    const destination = join(root, "restored");
    await expect(restore({ source: bundle, databaseUrl: url, storageRoot: destination })).rejects.toThrow("different");
    await restore({ source: bundle, databaseUrl: target.href, storageRoot: destination });
    restored = createDatabase(target.href);
    const restoredStorage = new LocalFileSystemStorage(destination);
    expect(await restoredStorage.read(doc.path)).toBe(saved.content);
    expect((await documentService(restored.db, restoredStorage).get(doc.id, workspaceId)).document).toEqual(saved.document);
    expect(await reviewService({ db: restored.db, storage: restoredStorage, provider: mockProvider() }).get(run.id, workspaceId)).toEqual(before);
    expect(await restored.db.select().from(quotes).where(eq(quotes.documentId, doc.id))).toEqual(await db.select().from(quotes).where(eq(quotes.documentId, doc.id)));
    expect(await restored.db.select().from(documentResources).where(eq(documentResources.documentId, doc.id))).toEqual(await db.select().from(documentResources).where(eq(documentResources.documentId, doc.id)));
    await expect(restore({ source: bundle, databaseUrl: target.href, storageRoot: join(root, "second") })).rejects.toThrow("empty");
    const path = join(bundle, "content", doc.path);
    const content = await readFile(path); await writeFile(path, "tampered");
    await expect(restore({ source: bundle, databaseUrl: target.href, storageRoot: join(root, "third") })).rejects.toThrow("checksum");
    await writeFile(path, content);
    expect(await storage.read(doc.path)).toBe(saved.content);
  } finally {
    await restored?.client.end();
    await db.delete(workspaces).where(eq(workspaces.id, workspaceId)); await client.end();
    if (created) await admin.unsafe(`DROP DATABASE "${targetName}"`);
    await admin.end(); await rm(root, { recursive: true, force: true });
  }
}, 30000);
