import { randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, beforeAll, expect, it, vi } from "vitest";
import { eq } from "drizzle-orm";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import { createDatabase } from "../../db/client";
import { workspaces, reviewRuns } from "../../db/schema";
import { readTestDatabaseUrl } from "../../lib/env";
import { LocalFileSystemStorage } from "../../modules/storage/local";
import { documentService, contentHash } from "../../modules/document/service";
import { resourceService } from "../../modules/resource/service";
import { reviewService } from "../../modules/review/service";
import { mockProvider } from "../../modules/review/mock-provider";
import { mockReviewFetcher } from "../../modules/review/fixtures";
const { db, client } = createDatabase(readTestDatabaseUrl()); const workspaceId = `reviews-${randomUUID()}`; let root: string; let storage: LocalFileSystemStorage;
beforeAll(async () => { root = await mkdtemp(join(tmpdir(), "kakudo-reviews-")); storage = new LocalFileSystemStorage(root); await migrate(db, { migrationsFolder: "./db/migrations" }); await db.insert(workspaces).values({ id: workspaceId, name: "Reviews" }); });
afterAll(async () => { await db.delete(workspaces).where(eq(workspaces.id, workspaceId)); await client.end(); await rm(root, { recursive: true, force: true }); });
it("pins revision/evidence snapshots through edits, persists findings and does not write content", async () => {
  const docs = documentService(db, storage); const content = "OAuthは認証プロトコルである。";
  const doc = await docs.create(workspaceId, { title: "Review note", content, nodeIds: [] });
  await resourceService(db).create(workspaceId, { url: "https://www.rfc-editor.org/rfc/rfc6749", title: "RFC 6749", type: "RFC" }, { kind: "document", id: doc.id });
  const search = { search: vi.fn(async () => []) }; const service = reviewService({ db, storage, provider: mockProvider(), fetcher: mockReviewFetcher, search });
  const job = await service.start(doc.id, workspaceId, { revisionId: doc.currentRevisionId!, type: "FACT_CHECK" }, false); expect(job.status).toBe("QUEUED");
  await docs.save(doc.id, workspaceId, { title: "Edited during review", content: "My revised understanding.", baseHash: contentHash(content) });
  await service.execute(job.id); const result = await service.get(job.id, workspaceId);
  expect(result.run.status).toBe("COMPLETED"); expect(result.stale).toBe(true); expect(result.revision.contentSnapshot).toBe(content);
  expect(result.findings[0].verdict).toBe("CONTRADICTED"); expect(result.findings[0].evidence[0].url).toBe("https://www.rfc-editor.org/rfc/rfc6749"); expect(search.search).not.toHaveBeenCalled();
  expect(await storage.read(doc.path)).toBe("My revised understanding.");
  await expect(service.start(doc.id, workspaceId, { revisionId: doc.currentRevisionId!, type: "FACT_CHECK" })).rejects.toThrow("保存");
  await expect(service.get(job.id, "other")).rejects.toThrow("not found");
  const other = await docs.create(workspaceId, { title: "Other", content: "", nodeIds: [] });
  await expect(db.insert(reviewRuns).values({ id: randomUUID(), documentId: other.id, revisionId: doc.currentRevisionId!, type: "FULL", provider: "mock" })).rejects.toThrow();
  await docs.remove(other.id, workspaceId); await docs.remove(doc.id, workspaceId);
});
it("records failure and permits a new run, with source-unavailable distinct from incorrect", async () => {
  const docs = documentService(db, storage); const doc = await docs.create(workspaceId, { title: "Failure", content: "Claim.", nodeIds: [] });
  const service = reviewService({ db, storage, provider: { ...mockProvider(), async extractClaims() { throw new Error("private secret"); } }, search: { async search() { return []; } } });
  const failed = await service.start(doc.id, workspaceId, { revisionId: doc.currentRevisionId!, type: "FACT_CHECK" }, false); await service.execute(failed.id);
  const result = await service.get(failed.id, workspaceId); expect(result.run.status).toBe("FAILED"); expect(result.run.error).not.toContain("private secret"); expect(result.findings).toHaveLength(0);
  const quoted = await docs.quote(doc.id, workspaceId, { title: "Failure", text: "Unavailable quote", sourceUrl: "http://127.0.0.1/", content: "Claim.", baseHash: contentHash("Claim."), from: 6, to: 6 });
  const next = await service.start(doc.id, workspaceId, { revisionId: quoted.document.currentRevisionId!, type: "SOURCE" }, false); await service.execute(next.id);
  expect((await service.get(next.id, workspaceId)).run.sourceChecks[0].status).toBe("UNAVAILABLE"); expect(await service.list(doc.id, workspaceId)).toHaveLength(2);
  await storage.write(doc.path, "external edit"); await expect(service.start(doc.id, workspaceId, { revisionId: quoted.document.currentRevisionId!, type: "SOURCE" })).rejects.toThrow("外部");
  await docs.remove(doc.id, workspaceId);
});
