import { afterEach, expect, it, vi } from 'vitest';
import { readNote } from '../../modules/document/reading';
import { request } from '../../client/api';
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); });

it('bounds one ignored-abort read at20seconds, reports once and never retries', async () => {
  vi.useFakeTimers(); let signal!: AbortSignal; const load = vi.fn((value: AbortSignal) => { signal = value; return new Promise<string>(() => {}); }); const onData = vi.fn(); const onError = vi.fn();
  const stop = readNote({ load, onData, onError }); await vi.advanceTimersByTimeAsync(19999); expect(onError).not.toHaveBeenCalled(); await vi.advanceTimersByTimeAsync(1); expect(onError).toHaveBeenCalledTimes(1); expect(onError.mock.calls[0][0].message).toContain('ノートの応答が時間内に届きませんでした'); expect(signal.aborted).toBe(true); expect(vi.getTimerCount()).toBe(0); await vi.advanceTimersByTimeAsync(60000); expect(load).toHaveBeenCalledTimes(1); expect(onData).not.toHaveBeenCalled(); expect(onError).toHaveBeenCalledTimes(1); stop();
});
it.each([false, true])('ignores a timed-out loader late settlement (failure=%s)', async failure => {
  vi.useFakeTimers(); let resolve!: (data: string) => void; let reject!: (error: Error) => void; const pending = new Promise<string>((yes, no) => { resolve = yes; reject = no; }); const onData = vi.fn(); const onError = vi.fn(); const stop = readNote({ load: () => pending, onData, onError }); await vi.advanceTimersByTimeAsync(20000); if (failure) reject(new Error('late private')); else resolve('old'); await vi.advanceTimersByTimeAsync(60000); expect(onData).not.toHaveBeenCalled(); expect(onError).toHaveBeenCalledTimes(1); expect(vi.getTimerCount()).toBe(0); stop();
});
it.each([false, true])('scope cleanup aborts and clears deadline; late settlement cannot touch replacement (failure=%s)', async failure => {
  vi.useFakeTimers(); let resolve!: (data: string) => void; let reject!: (error: Error) => void; let signal!: AbortSignal; const pending = new Promise<string>((yes, no) => { resolve = yes; reject = no; }); const onData = vi.fn(); const onError = vi.fn(); const stopOld = readNote({ load: value => { signal = value; return pending; }, onData, onError }); stopOld(); expect(signal.aborted).toBe(true); expect(vi.getTimerCount()).toBe(0); const stopNew = readNote({ load: async () => 'current', onData, onError }); await vi.advanceTimersByTimeAsync(0); if (failure) reject(new Error('late private')); else resolve('old'); await vi.advanceTimersByTimeAsync(60000); expect(onData).toHaveBeenCalledExactlyOnceWith('current'); expect(onError).not.toHaveBeenCalled(); expect(vi.getTimerCount()).toBe(0); stopNew();
});
it('success just before the deadline clears its timer and reads only once', async () => {
  vi.useFakeTimers(); let resolve!: (data: string) => void; const pending = new Promise<string>(yes => { resolve = yes; }); const onData = vi.fn(); const onError = vi.fn(); const load = vi.fn(() => pending); const stop = readNote({ load, onData, onError }); await vi.advanceTimersByTimeAsync(19999); resolve('current'); await vi.advanceTimersByTimeAsync(60000); expect(onData).toHaveBeenCalledExactlyOnceWith('current'); expect(onError).not.toHaveBeenCalled(); expect(vi.getTimerCount()).toBe(0); expect(load).toHaveBeenCalledTimes(1); stop();
});
it('timeout and abort rejection converge on one safe failure without leaking diagnostics', async () => {
  vi.useFakeTimers(); const onError = vi.fn(); const stop = readNote({ load: signal => new Promise<never>((_, reject) => { signal.addEventListener('abort', () => reject(new Error('private loader')), { once: true }); }), onData: vi.fn(), onError }); await vi.advanceTimersByTimeAsync(20000); expect(onError).toHaveBeenCalledTimes(1); expect(onError.mock.calls[0][0].message).toContain('ノートの応答が時間内に届きませんでした'); expect(onError.mock.calls[0][0].message).not.toContain('private'); expect(vi.getTimerCount()).toBe(0); stop();
});
it('synchronous loader and schema failure has one safe failure and clears deadline', async () => {
  vi.useFakeTimers(); const onError = vi.fn(); const stop = readNote({ load: () => { throw new Error('private schema/response'); }, onData: vi.fn(), onError }); await vi.advanceTimersByTimeAsync(60000); expect(onError).toHaveBeenCalledTimes(1); expect(onError.mock.calls[0][0].message).toBe('ノートを読み取れませんでした。接続や対象を確認して再取得してください。'); expect(vi.getTimerCount()).toBe(0); stop();
});
it('the existing GET request JSON-body read shares the deadline and explicit replacement is one GET', async () => {
  vi.useFakeTimers(); let finishBody!: (data: unknown) => void; const body = new Promise(resolve => { finishBody = resolve; }); const fetchMock = vi.fn().mockResolvedValueOnce({ ok: true, status: 200, json: () => body }).mockResolvedValue({ ok: true, status: 200, json: async () => ({ content: 'current human note' }) }); vi.stubGlobal('fetch', fetchMock); const onData = vi.fn(); const onError = vi.fn(); const load = (signal: AbortSignal) => request('/documents/note?workspaceId=own', 'GET', undefined, { signal }); const stopOld = readNote({ load, onData, onError }); await vi.advanceTimersByTimeAsync(20000); expect(onError).toHaveBeenCalledTimes(1); expect(fetchMock.mock.calls[0][1].signal.aborted).toBe(true); stopOld(); const stopNew = readNote({ load, onData, onError }); await vi.advanceTimersByTimeAsync(0); finishBody({ content: 'old' }); await vi.advanceTimersByTimeAsync(60000); expect(onData).toHaveBeenCalledExactlyOnceWith({ content: 'current human note' }); expect(onError).toHaveBeenCalledTimes(1); expect(fetchMock).toHaveBeenCalledTimes(2); expect(fetchMock.mock.calls.every(([, options]) => options.method === 'GET')).toBe(true); expect(vi.getTimerCount()).toBe(0); stopNew();
});
